// Generated by CoffeeScript 2.4.1
(function() {
  var Main, cheerio, db, fs, iconv, initPuppeteerPool, insert, m, pool, puppeteer, run, sqlite, tgt;

  Main = (function() {
    var data;

    class Main {
      each(callback) {
        var d, i, len, results;
        results = [];
        for (i = 0, len = data.length; i < len; i++) {
          d = data[i];
          results.push(callback(d));
        }
        return results;
      }

    };

    data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

    return Main;

  }).call(this);

  m = new Main();

  m.each(function(d) {
    return console.log(d);
  });

  console.log('fk');

  iconv = require('iconv-lite');

  cheerio = require('cheerio');

  puppeteer = require('puppeteer');

  fs = require('fs');

  sqlite = require('sqlite3');

  initPuppeteerPool = require('./puppeteer-pool.js');

  pool = initPuppeteerPool({
    puppeteerArgs: {
      ignoreHTTPSErrors: true,
      headless: true,
      timeout: 0,
      pipe: true
    }
  });

  tgt = 'table.w782.comm.lsjz';

  db = new sqlite.Database('/home/wang/文档/database/data.db');

  insert = function(t, d, v) {
    return db.serialize(function() {
      var stmt;
      stmt = db.prepare('INSERT INTO info2 VALUES(?, ?, ?)');
      stmt.run(t, d, v, function(err) {});
      return stmt.finalize();
    });
  };

  run = async function(html, tk) {
    var $, tbody;
    $ = (await cheerio.load(html));
    tbody = $(tgt).children()[1];
    return $(tbody).children().each(function(ind, ele) {
      var day, tds, value;
      tds = $(ele).children();
      // 日期
      day = $(tds[0]).text();
      // 单位净值
      value = $(tds[1]).text().slice(0, 6);
      // 日增长率
      return insert(tk, day, value);
    });
  };

  db.serialize(function() {
    var LIMIT, iter_times;
    iter_times = 0;
    LIMIT = 5;
    db.get("SELECT COUNT(*) AS num FROM fund", function(err, res) {
      console.log(res);
      return LIMIT = res.num;
    });
    return db.each("SELECT ticket FROM fund", async function(err, row) {
      var tk;
      tk = row.ticket;
      return (await pool.use(async function(instance) {
        var html, page, url;
        page = (await instance.newPage());
        url = `http://fundf10.eastmoney.com/jjjz_${tk}.html`;
        await page.goto(url);
        html = (await page.content());
        await page.close();
        await run(html, tk);
        iter_times += 1;
        if (iter_times === LIMIT) {
          console.log('ok');
          pool.drain().then(() => {
            return pool.clear();
          });
          return console.log('done');
        }
      }));
    });
  });

}).call(this);

//# sourceMappingURL=Main.js.map
