// Generated by CoffeeScript 2.4.1
(function() {
  var cheerio, initPuppeteerPool, pool, spyfun;

  cheerio = require('cheerio');

  initPuppeteerPool = require('./puppeteer-pool.js');

  pool = initPuppeteerPool({
    puppeteerArgs: {
      ignoreHTTPSErrors: true,
      headless: true,
      timeout: 0,
      pipe: true
    }
  });

  spyfun = async function(url, callback) {
    return (await pool.use(async function(instance) {
      var html, page;
      page = (await instance.newPage());
      await page.goto(url);
      html = (await page.content());
      await page.close();
      return callback(html);
    }));
  };

  module.exports = spyfun;

}).call(this);

//# sourceMappingURL=MySpider.js.map
