// Generated by CoffeeScript 2.4.1
(function() {
  var client, redis;

  redis = require('redis');

  client = redis.createClient('6379', '127.0.0.1');

  client.on('error', function(err) {
    return console.log(err);
  });

  client.get('001237', function(err, data) {
    console.log(data);
    return client.quit();
  });

  client.get('000001', function(err, data) {
    console.log(data);
    return client.quit();
  });

}).call(this);

//# sourceMappingURL=read.js.map
