// Generated by CoffeeScript 2.4.1
(function() {
  var cheerio, db, fs, iconv, insert, puppeteer, reg, run, sqlite, tgt;

  iconv = require('iconv-lite');

  cheerio = require('cheerio');

  puppeteer = require('puppeteer');

  fs = require('fs');

  sqlite = require('sqlite3');

  tgt = 'table.w782.comm.lsjz';

  reg = /d/;

  db = new sqlite.Database('/home/wang/文档/database/data.db');

  insert = function(t, d, v, r) {
    return db.serialize(function() {
      var stmt;
      stmt = db.prepare('INSERT INTO info VALUES(?, ?, ?, ?)');
      stmt.run(t, d, v, r, function(err) {
        return fs.writeFile('bug.log', err, {
          'flag': 'a'
        }, function(er) {});
      });
      return stmt.finalize();
    });
  };

  run = async function(tk) {
    var $, browser, html, page, tbody, url;
    url = `http://fundf10.eastmoney.com/jjjz_${tk}.html`;
    browser = (await puppeteer.launch());
    page = (await browser.newPage());
    await page.goto(url);
    html = (await page.content());
    await browser.close();
    $ = (await cheerio.load(html));
    tbody = $(tgt).children()[1];
    return $(tbody).children().each(function(ind, ele) {
      var day, rate, tds, value;
      tds = $(ele).children();
      // 日期
      day = $(tds[0]).text();
      // 单位净值
      value = $(tds[1]).text().slice(0, 6);
      // 日增长率
      rate = $(tds[3]).text();
      return insert(tk, day, value, rate);
    });
  };

  db.serialize(function() {
    return db.each("SELECT ticket FROM fund LIMIT 51 OFFSET 150", function(err, row) {
      var ticket;
      ticket = row.ticket;
      return run(ticket);
    });
  });

}).call(this);

//# sourceMappingURL=readValue.js.map
