// Generated by CoffeeScript 2.4.1
(function() {
  var cheerio, db, fs, iconv, initPuppeteerPool, insert, pool, puppeteer, sqlite, tgt;

  iconv = require('iconv-lite');

  cheerio = require('cheerio');

  puppeteer = require('puppeteer');

  fs = require('fs');

  sqlite = require('sqlite3');

  initPuppeteerPool = require('./puppeteer-pool.js');

  pool = initPuppeteerPool({
    puppeteerArgs: {
      ignoreHTTPSErrors: true,
      headless: true,
      timeout: 0,
      pipe: true
    }
  });

  tgt = 'table.w782.comm.lsjz';

  db = new sqlite.Database('/home/wang/文档/database/data.db');

  insert = function(t, d, v, r) {
    return db.serialize(function() {
      var stmt;
      stmt = db.prepare('INSERT INTO info VALUES(?, ?, ?, ?)');
      stmt.run(t, d, v, r, function(err) {});
      return stmt.finalize();
    });
  };

  db.each("SELECT ticket FROM fund", async function(err, row) {
    var tk;
    tk = row.ticket;
    return (await pool.use(async function(instance) {
      var $, html, page, tbody, url;
      page = (await instance.newPage());
      url = `http://fundf10.eastmoney.com/jjjz_${tk}.html`;
      await page.goto(url);
      html = (await page.content());
      await page.close();
      $ = (await cheerio.load(html));
      tbody = $(tgt).children()[1];
      return $(tbody).children().each(function(ind, ele) {
        var day, rate, tds, value;
        tds = $(ele).children();
        // 日期
        day = $(tds[0]).text();
        // 单位净值
        value = $(tds[1]).text().slice(0, 6);
        // 日增长率
        rate = $(tds[3]).text();
        return insert(tk, day, value, rate);
      });
    }));
  });

  //if i is LIMIT_TIMES
// pool.drain().then(() => pool.clear())

}).call(this);

//# sourceMappingURL=SuperSpider.js.map
