// Generated by CoffeeScript 2.4.1
(function() {
  var buy, buy_aa, out, out_aa, run, work, work_aa;

  buy = function() {
    console.log('开始买笔');
    return new Promise(function(resolve, reject) {
      return setTimeout(function() {
        console.log('买了笔');
        return resolve('数学作业');
      }, 1000);
    });
  };

  work = function(data) {
    console.log('开始写作业' + data);
    return new Promise(function(resolve, reject) {
      return setTimeout(function() {
        console.log('写完作业');
        return resolve('作业本');
      }, 1000);
    });
  };

  out = function(data) {
    console.log('开始上交' + data);
    return new Promise(function(resolve, reject) {
      return setTimeout(function() {
        console.log('上交完毕');
        return resolve('得分A');
      }, 1000);
    });
  };

  buy().then(work).then(out).then(function(data) {
    return console.log(data);
  });

  buy_aa = async function() {
    console.log('开始买笔');
    return (await setTimeout(function() {
      console.log('买了笔');
      return '数学作业';
    }, 1000));
  };

  work_aa = async function() {
    console.log('开始写作业' + (await buy_aa()));
    return (await setTimeout(function() {
      console.log('写完作业');
      return '作业本';
    }, 1000));
  };

  out_aa = async function() {
    console.log('开始上交' + (await work_aa()));
    return (await setTimeout(function() {
      console.log('上交完毕');
      return '得分A';
    }, 1000));
  };

  run = async function() {
    return console.log((await out_aa()));
  };

  run();

}).call(this);

//# sourceMappingURL=test2.js.map
